version: "3.9"

services:
  fpm:
    image: app/php-fpm:develop
    build:
      context: .
    environment:
      SVC_WAIT_MYSQL: mysql:3306
      APP_ENV: dev
    volumes:
      - ./app:/app
      - ./xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - default
    depends_on:
      - mysql
      - rabbitmq
      - redis

  test:
    image: app/php-fpm:develop
    build:
      context: .
    environment:
      SVC_WAIT_MYSQL: mysql:3306
      APP_ENV: test
    volumes:
      - ./app:/app
      - ./xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - default
    depends_on:
      - mysql
      - rabbitmq
      - redis

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - fpm
    ports:
      - "80:80"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    networks:
      - default
    ports:
      - "3360:3306"

  redis:
    image: redis:6.0-alpine
    hostname: redis
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_VHOST: app
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management path_prefix "/rabbitmq"'
    networks:
      - default

networks:
  default:
